[versions]
mod-version = "1.0.0"

# Fabric (https://fabricmc.net/develop)
jdk = "21"
minecraft = "1.21.4"
yarn-mappings = "1.21.4+build.8"
fabric-loader = "0.16.10"

# Loom (https://github.com/FabricMC/fabric-loom)
loom = "1.9-SNAPSHOT"

# Meteor (https://github.com/MeteorDevelopment/meteor-client/)
meteor = "1.21.4-SNAPSHOT"

[libraries]
# Fabric base
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn = { module = "net.fabricmc:yarn", version.ref = "yarn-mappings" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

# Meteor client
meteor-client = { module = "meteordevelopment:meteor-client", version.ref = "meteor" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "loom" }
